[theme]
base                  = "dark"
backgroundColor       = "#0e1117"
secondaryBackgroundColor = "#13161f"
textColor             = "#ffffff"
primaryColor          = "#FFD700"
font                  = "sans serif"

[server]
headless              = true
enableXsrfProtection  = true

[browser]
gatherUsageStats      = false
